import { htmlEscape } from '../utils/html.js';
export function renderIpPage({ authenticated, visits }) {
  if (!authenticated) return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>IP 访问记录登录</title><style>body{margin:0;background:#0f0f1a;color:#e5e7eb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif;min-height:100vh;display:flex;align-items:center;justify-content:center}.box{width:360px;background:#1a1a2e;border:1px solid #2a2a4a;border-radius:16px;padding:36px}h1{font-size:20px;text-align:center;margin:0 0 22px}input{width:100%;box-sizing:border-box;padding:12px 14px;border-radius:8px;border:1px solid #2a2a4a;background:#0f0f1a;color:#fff;font-size:15px;margin-bottom:12px}button{width:100%;padding:12px;border:0;border-radius:8px;background:#0066ff;color:#fff;font-size:15px;cursor:pointer}.msg{display:none;margin-bottom:12px;color:#ff6b6b;font-size:14px;text-align:center}.back{display:block;text-align:center;margin-top:16px;color:#60a5fa;text-decoration:none;font-size:14px}</style></head><body><div class="box"><h1>🔐 查看访问 IP</h1><input id="pwd" type="password" placeholder="输入后台密码" onkeydown="if(event.key==='Enter')login()"><div id="msg" class="msg"></div><button onclick="login()">登录查看</button><a class="back" href="/admin/">返回后台</a></div><script>async function login(){const p=document.getElementById('pwd').value;const r=await fetch('/api/admin/login',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({password:p})});if(r.ok){location.reload()}else{const m=document.getElementById('msg');m.textContent='密码错误';m.style.display='block'}}</script></body></html>`;
  const groups = new Map();
  const days = Object.keys(visits).sort().reverse();
  for (const day of days) for (const v of (visits[day].visitors || [])) {
    const key = v.ip || '未知';
    if (!groups.has(key)) groups.set(key, { ip: key, location: v.location || '', total: 0, firstTime: v.firstTime || '', lastTime: v.lastTime || '', device: `${v.device || ''} / ${v.os || ''} / ${v.browser || ''}`, userAgent: v.userAgent || '', details: [] });
    const g = groups.get(key); g.total += (v.hits || 1); if ((v.lastTime || '') > (g.lastTime || '')) g.lastTime = v.lastTime; if (!g.firstTime || (v.firstTime || '') < g.firstTime) g.firstTime = v.firstTime || g.firstTime;
    for (const h of (v.history || [])) g.details.push({ day, time: h.time || '', method: h.method || v.method || '', path: h.path || v.path || '', referer: h.referer || v.referer || '', device: `${v.device || ''} / ${v.os || ''} / ${v.browser || ''}`, ua: v.userAgent || '' });
  }
  const list = [...groups.values()].sort((a,b) => b.total - a.total || String(b.lastTime).localeCompare(String(a.lastTime)));
  const rows = list.map((g, idx) => {
    const details = g.details.sort((a,b) => String(b.time).localeCompare(String(a.time))).map(d => `<tr class="detail detail-${idx}"><td></td><td colspan="8"><b>${htmlEscape(d.day)} ${htmlEscape(d.time)}</b>　${htmlEscape(d.method)}　${htmlEscape(d.path)}　来源：${htmlEscape(d.referer || '-')}<br><span class="ua">${htmlEscape(d.device)}　${htmlEscape(d.ua)}</span></td></tr>`).join('');
    return `<tr class="main" onclick="toggleDetail(${idx})"><td>▶</td><td>${htmlEscape(g.ip)}</td><td>${htmlEscape(g.location)}</td><td class="count">${htmlEscape(g.total)}</td><td>${htmlEscape(g.firstTime)}</td><td>${htmlEscape(g.lastTime)}</td><td>${htmlEscape(g.device)}</td><td class="ua">${htmlEscape(g.userAgent)}</td></tr>${details}`;
  }).join('');
  return `<!doctype html><html lang="zh-CN"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>访问 IP 记录</title><style>body{margin:0;background:#0f0f1a;color:#e5e7eb;font-family:-apple-system,BlinkMacSystemFont,'Segoe UI',sans-serif}.wrap{padding:24px;max-width:1500px;margin:auto}h1{font-size:22px}.top{display:flex;justify-content:space-between;align-items:center;margin-bottom:18px}a{color:#60a5fa}.card{background:#1a1a2e;border:1px solid #2a2a4a;border-radius:12px;overflow:auto}table{width:100%;border-collapse:collapse;font-size:13px}th,td{padding:10px 12px;border-bottom:1px solid #2a2a4a;text-align:left;vertical-align:top;white-space:nowrap}th{background:#111827;color:#93c5fd;position:sticky;top:0}.ua{white-space:normal;min-width:360px;color:#b6bdd0}.main{cursor:pointer}.main:hover{background:#20203a}.detail{display:none;background:#111827}.detail td{color:#cbd5e1}.count{font-size:18px;font-weight:700;color:#60a5fa}.muted{color:#9ca3af;font-size:13px}</style></head><body><div class="wrap"><div class="top"><div><h1>访问 IP 记录</h1><div class="muted">按 IP 汇总总访问次数；点击 IP 行可展开查看每天每次访问时间、路径、来源。</div></div><a href="/admin/">返回后台</a></div><div class="card"><table><thead><tr><th></th><th>IP</th><th>归属地</th><th>总访问</th><th>首次访问</th><th>最后访问</th><th>设备</th><th>User-Agent</th></tr></thead><tbody>${rows || '<tr><td colspan="8">暂无记录</td></tr>'}</tbody></table></div></div><script>function toggleDetail(i){document.querySelectorAll('.detail-'+i).forEach(e=>{e.style.display=e.style.display==='table-row'?'none':'table-row'})}</script></body></html>`;
}
